version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
        #environment:
        #MONGO_INITDB_ROOT_USERNAME: root
        #MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    ports:
      - "5000:5000"

  consumer_one:
    build:
      context: .
      dockerfile: consumer_one/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example

  consumer_two:
    build:
      context: .
      dockerfile: consumer_two/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example

  consumer_three:
    build:
      context: .
      dockerfile: consumer_three/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      
  consumer_four:
    build:
      context: .
      dockerfile: consumer_four/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
